version: 2 # use CircleCI 2.0
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
        name: Run test
        command: go test